version: '3.8'
services:
  maria-db:
    image: mariadb:10.11
    container_name: maria-db
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: fe83d2afe7e1b4a547584bb80b35b3525456e5d120fa7e50508f6529058c3b85
      MYSQL_DATABASE: lafamilia
      MYSQL_USER: root
      MYSQL_PASSWORD: fe83d2afe7e1b4a547584bb80b35b3525456e5d120fa7e50508f6529058c3b85
    volumes:
      - db_data_lafamilia:/var/lib/mysql
      - ./database/initdb.d:/docker-entrypoint-initdb.d

  pma:
    image: phpmyadmin/phpmyadmin:5.2.1
    restart: always
    ports:
      - "3082:80"
    depends_on:
      - maria-db
    environment:
      PMA_HOST: maria-db
      PMA_USER: root
      PMA_PASSWORD: fe83d2afe7e1b4a547584bb80b35b3525456e5d120fa7e50508f6529058c3b85

volumes:
  db_data_lafamilia:
